// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/model/gtfs/agency.dart';
import 'data/model/gtfs/calendar.dart';
import 'data/model/gtfs/calendar_date.dart';
import 'data/model/gtfs/route.dart';
import 'data/model/gtfs/shape.dart';
import 'data/model/gtfs/stop.dart';
import 'data/model/gtfs/stop_time.dart';
import 'data/model/gtfs/trip.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1269804270028023658),
    name: 'Agency',
    lastPropertyId: const obx_int.IdUid(9, 4159161026258427815),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3858248111872154133),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 695342226961832644),
        name: 'agencyId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 1100375494064142434),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 66972578086276643),
        name: 'agencyName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6233417420337434368),
        name: 'agencyUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5296407997614410779),
        name: 'agencyTimezone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 682075405615714157),
        name: 'agencyLang',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1751922983146593306),
        name: 'agencyPhone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8507548661716846179),
        name: 'agencyFareUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4159161026258427815),
        name: 'agencyEmail',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 834328462759150831),
    name: 'Calendar',
    lastPropertyId: const obx_int.IdUid(12, 6899903814158733115),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1230562664950417401),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1873649963410237941),
        name: 'serviceId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 5243539200281329449),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3087885390177559993),
        name: 'monday',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4435209780984722406),
        name: 'tuesday',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8909001731674242827),
        name: 'wednesday',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4446141868252198073),
        name: 'thursday',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7600826583828867603),
        name: 'friday',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2002734388357714001),
        name: 'saturday',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6726209614836306991),
        name: 'sunday',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3442641860357834039),
        name: 'startDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8227358584776018771),
        name: 'endDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6899903814158733115),
        name: 'agencyId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(16, 4156923600506695243),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 5105124661776014878),
    name: 'CalendarDate',
    lastPropertyId: const obx_int.IdUid(5, 3165865166506201376),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5169492270812698366),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3788715290122025679),
        name: 'serviceId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 1026976800816446039),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6792538423887725710),
        name: 'date',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 3203605543231455161),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1665250117674130791),
        name: 'exceptionType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3165865166506201376),
        name: 'agencyId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(17, 5180858775171188704),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8909194735816257089),
    name: 'Route',
    lastPropertyId: const obx_int.IdUid(16, 3811352962163632300),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1138783610873718802),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1995720068215000242),
        name: 'routeId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 8746295149108304400),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8213986057091169162),
        name: 'routeShortName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6264357829784579398),
        name: 'routeLongName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6059528024396236623),
        name: 'routeDesc',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 9203162364261776369),
        name: 'routeType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7231105109319842390),
        name: 'routeUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1885964337932417745),
        name: 'routeColor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 780163569024016318),
        name: 'routeTextColor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5246243476437150214),
        name: 'routeSortOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7376660672365340951),
        name: 'continuousPickup',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4582029470017833223),
        name: 'continuousDropOff',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4177346445432147246),
        name: 'networkId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 6097706445388394635),
        name: 'agencyId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 2100797992360167143),
        relationField: 'agency',
        relationTarget: 'Agency',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 3811352962163632300),
        name: 'agencyIdString',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(15, 2069121436681577850),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 106232920832538326),
    name: 'Shape',
    lastPropertyId: const obx_int.IdUid(7, 4607428091517340150),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8570555886010149370),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5945389610853240326),
        name: 'shapeId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 6451034992393938851),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2218707231934733932),
        name: 'lat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6843403529644872666),
        name: 'lon',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8228515365392180934),
        name: 'sequence',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2052129921837559311),
        name: 'distTraveled',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4607428091517340150),
        name: 'agencyId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(18, 2995388910594367756),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 3894510792602689502),
    name: 'Stop',
    lastPropertyId: const obx_int.IdUid(17, 8570958667179685468),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5129257249130005052),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3642812690262401939),
        name: 'stopId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(8, 2254058391020790304),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4929282847944689818),
        name: 'code',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4846442538335317600),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1265553340396385399),
        name: 'ttsName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 822485542130197204),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3936719594003916786),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3403157120496069153),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1676563008837070520),
        name: 'zoneId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 193546834944748198),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5826424709638503150),
        name: 'locationType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6587183300412988253),
        name: 'parentStation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7413927546641215152),
        name: 'timezone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4265713450655448646),
        name: 'wheelchairBoarding',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7288976160362726446),
        name: 'levelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 3518069796946663095),
        name: 'platformCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 8570958667179685468),
        name: 'agencyId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(19, 6983733318572626293),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 4334486746841726229),
    name: 'StopTime',
    lastPropertyId: const obx_int.IdUid(21, 8037643912342971963),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3353402531375076065),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 774816390683673924),
        name: 'tripGtfsId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(9, 7594095006785765186),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1098774507729088738),
        name: 'arrivalTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7807275240270483828),
        name: 'departureTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 734357243021527064),
        name: 'stopGtfsId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1500696527634231101),
        name: 'locationGroupId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5476686049121639181),
        name: 'locationId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2365304306469763930),
        name: 'stopSequence',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 309570630033632807),
        name: 'stopHeadsign',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3078937473011363705),
        name: 'startPickupDropOffWindow',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1551738279017153245),
        name: 'endPickupDropOffWindow',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8886584695540907337),
        name: 'pickupType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7706572035765674607),
        name: 'dropOffType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3454408870231294282),
        name: 'continuousPickup',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4362985350560859965),
        name: 'continuousDropOff',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 1961543507055658224),
        name: 'shapeDistTraveled',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 454155805372054886),
        name: 'timepoint',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 8540801245367533145),
        name: 'pickupBookingRuleId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 6904235155483506128),
        name: 'dropOffBookingRuleId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 3552689535336499953),
        name: 'tripId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(10, 7421512569025365809),
        relationField: 'trip',
        relationTarget: 'Trip',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 8037643912342971963),
        name: 'stopId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(11, 7472490991486053878),
        relationField: 'stop',
        relationTarget: 'Stop',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 6414245339417216490),
    name: 'Trip',
    lastPropertyId: const obx_int.IdUid(14, 3423953634144993121),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7655489436274231621),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3892736331373273780),
        name: 'tripId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(12, 7854772513045791350),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2643807982993320692),
        name: 'routeGtfsId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8603562233644214185),
        name: 'serviceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7656723632111214592),
        name: 'headsign',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5272055183087298722),
        name: 'shortName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8395632337338258493),
        name: 'directionId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2869219538517847587),
        name: 'blockId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7157827764748454014),
        name: 'shapeId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4390202176001392139),
        name: 'wheelchairAccessible',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 191335554637255309),
        name: 'bikesAllowed',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8652917155543184810),
        name: 'carsAllowed',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6986166041337948758),
        name: 'routeId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(13, 4058094376980156172),
        relationField: 'route',
        relationTarget: 'Route',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3423953634144993121),
        name: 'calendarId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(14, 8823535123838157287),
        relationField: 'calendar',
        relationTarget: 'Calendar',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(8, 6414245339417216490),
    lastIndexId: const obx_int.IdUid(19, 6983733318572626293),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [7815885747105559944],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Agency: obx_int.EntityDefinition<Agency>(
      model: _entities[0],
      toOneRelations: (Agency object) => [],
      toManyRelations: (Agency object) => {},
      getId: (Agency object) => object.id,
      setId: (Agency object, int id) {
        object.id = id;
      },
      objectToFB: (Agency object, fb.Builder fbb) {
        final agencyIdOffset = fbb.writeString(object.agencyId);
        final agencyNameOffset = fbb.writeString(object.agencyName);
        final agencyUrlOffset = fbb.writeString(object.agencyUrl);
        final agencyTimezoneOffset = fbb.writeString(object.agencyTimezone);
        final agencyLangOffset = object.agencyLang == null
            ? null
            : fbb.writeString(object.agencyLang!);
        final agencyPhoneOffset = object.agencyPhone == null
            ? null
            : fbb.writeString(object.agencyPhone!);
        final agencyFareUrlOffset = object.agencyFareUrl == null
            ? null
            : fbb.writeString(object.agencyFareUrl!);
        final agencyEmailOffset = object.agencyEmail == null
            ? null
            : fbb.writeString(object.agencyEmail!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, agencyIdOffset);
        fbb.addOffset(2, agencyNameOffset);
        fbb.addOffset(3, agencyUrlOffset);
        fbb.addOffset(4, agencyTimezoneOffset);
        fbb.addOffset(5, agencyLangOffset);
        fbb.addOffset(6, agencyPhoneOffset);
        fbb.addOffset(7, agencyFareUrlOffset);
        fbb.addOffset(8, agencyEmailOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final agencyIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final agencyNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final agencyUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final agencyTimezoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final agencyLangParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final agencyPhoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final agencyFareUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final agencyEmailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = Agency(
          id: idParam,
          agencyId: agencyIdParam,
          agencyName: agencyNameParam,
          agencyUrl: agencyUrlParam,
          agencyTimezone: agencyTimezoneParam,
          agencyLang: agencyLangParam,
          agencyPhone: agencyPhoneParam,
          agencyFareUrl: agencyFareUrlParam,
          agencyEmail: agencyEmailParam,
        );

        return object;
      },
    ),
    Calendar: obx_int.EntityDefinition<Calendar>(
      model: _entities[1],
      toOneRelations: (Calendar object) => [],
      toManyRelations: (Calendar object) => {},
      getId: (Calendar object) => object.id,
      setId: (Calendar object, int id) {
        object.id = id;
      },
      objectToFB: (Calendar object, fb.Builder fbb) {
        final serviceIdOffset = fbb.writeString(object.serviceId);
        final startDateOffset = fbb.writeString(object.startDate);
        final endDateOffset = fbb.writeString(object.endDate);
        final agencyIdOffset = object.agencyId == null
            ? null
            : fbb.writeString(object.agencyId!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, serviceIdOffset);
        fbb.addInt64(2, object.monday);
        fbb.addInt64(3, object.tuesday);
        fbb.addInt64(4, object.wednesday);
        fbb.addInt64(5, object.thursday);
        fbb.addInt64(6, object.friday);
        fbb.addInt64(7, object.saturday);
        fbb.addInt64(8, object.sunday);
        fbb.addOffset(9, startDateOffset);
        fbb.addOffset(10, endDateOffset);
        fbb.addOffset(11, agencyIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final serviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final agencyIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final mondayParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final tuesdayParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final wednesdayParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final thursdayParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final fridayParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final saturdayParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final sundayParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final startDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final endDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final object = Calendar(
          id: idParam,
          serviceId: serviceIdParam,
          agencyId: agencyIdParam,
          monday: mondayParam,
          tuesday: tuesdayParam,
          wednesday: wednesdayParam,
          thursday: thursdayParam,
          friday: fridayParam,
          saturday: saturdayParam,
          sunday: sundayParam,
          startDate: startDateParam,
          endDate: endDateParam,
        );

        return object;
      },
    ),
    CalendarDate: obx_int.EntityDefinition<CalendarDate>(
      model: _entities[2],
      toOneRelations: (CalendarDate object) => [],
      toManyRelations: (CalendarDate object) => {},
      getId: (CalendarDate object) => object.id,
      setId: (CalendarDate object, int id) {
        object.id = id;
      },
      objectToFB: (CalendarDate object, fb.Builder fbb) {
        final serviceIdOffset = fbb.writeString(object.serviceId);
        final dateOffset = fbb.writeString(object.date);
        final agencyIdOffset = object.agencyId == null
            ? null
            : fbb.writeString(object.agencyId!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, serviceIdOffset);
        fbb.addOffset(2, dateOffset);
        fbb.addInt64(3, object.exceptionType);
        fbb.addOffset(4, agencyIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final serviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final agencyIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final dateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final exceptionTypeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = CalendarDate(
          id: idParam,
          serviceId: serviceIdParam,
          agencyId: agencyIdParam,
          date: dateParam,
          exceptionType: exceptionTypeParam,
        );

        return object;
      },
    ),
    Route: obx_int.EntityDefinition<Route>(
      model: _entities[3],
      toOneRelations: (Route object) => [object.agency],
      toManyRelations: (Route object) => {},
      getId: (Route object) => object.id,
      setId: (Route object, int id) {
        object.id = id;
      },
      objectToFB: (Route object, fb.Builder fbb) {
        final routeIdOffset = fbb.writeString(object.routeId);
        final routeShortNameOffset = object.routeShortName == null
            ? null
            : fbb.writeString(object.routeShortName!);
        final routeLongNameOffset = object.routeLongName == null
            ? null
            : fbb.writeString(object.routeLongName!);
        final routeDescOffset = object.routeDesc == null
            ? null
            : fbb.writeString(object.routeDesc!);
        final routeUrlOffset = object.routeUrl == null
            ? null
            : fbb.writeString(object.routeUrl!);
        final routeColorOffset = object.routeColor == null
            ? null
            : fbb.writeString(object.routeColor!);
        final routeTextColorOffset = object.routeTextColor == null
            ? null
            : fbb.writeString(object.routeTextColor!);
        final networkIdOffset = object.networkId == null
            ? null
            : fbb.writeString(object.networkId!);
        final agencyIdStringOffset = object.agencyIdString == null
            ? null
            : fbb.writeString(object.agencyIdString!);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, routeIdOffset);
        fbb.addOffset(3, routeShortNameOffset);
        fbb.addOffset(4, routeLongNameOffset);
        fbb.addOffset(5, routeDescOffset);
        fbb.addInt64(6, object.routeType);
        fbb.addOffset(7, routeUrlOffset);
        fbb.addOffset(8, routeColorOffset);
        fbb.addOffset(9, routeTextColorOffset);
        fbb.addInt64(10, object.routeSortOrder);
        fbb.addInt64(11, object.continuousPickup);
        fbb.addInt64(12, object.continuousDropOff);
        fbb.addOffset(13, networkIdOffset);
        fbb.addInt64(14, object.agency.targetId);
        fbb.addOffset(15, agencyIdStringOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final routeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final agencyIdStringParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final routeShortNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final routeLongNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final routeDescParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final routeTypeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final routeUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final routeColorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final routeTextColorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final routeSortOrderParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final continuousPickupParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final continuousDropOffParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final networkIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final object = Route(
          id: idParam,
          routeId: routeIdParam,
          agencyIdString: agencyIdStringParam,
          routeShortName: routeShortNameParam,
          routeLongName: routeLongNameParam,
          routeDesc: routeDescParam,
          routeType: routeTypeParam,
          routeUrl: routeUrlParam,
          routeColor: routeColorParam,
          routeTextColor: routeTextColorParam,
          routeSortOrder: routeSortOrderParam,
          continuousPickup: continuousPickupParam,
          continuousDropOff: continuousDropOffParam,
          networkId: networkIdParam,
        );
        object.agency.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        object.agency.attach(store);
        return object;
      },
    ),
    Shape: obx_int.EntityDefinition<Shape>(
      model: _entities[4],
      toOneRelations: (Shape object) => [],
      toManyRelations: (Shape object) => {},
      getId: (Shape object) => object.id,
      setId: (Shape object, int id) {
        object.id = id;
      },
      objectToFB: (Shape object, fb.Builder fbb) {
        final shapeIdOffset = fbb.writeString(object.shapeId);
        final agencyIdOffset = object.agencyId == null
            ? null
            : fbb.writeString(object.agencyId!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, shapeIdOffset);
        fbb.addFloat64(2, object.lat);
        fbb.addFloat64(3, object.lon);
        fbb.addInt64(4, object.sequence);
        fbb.addFloat64(5, object.distTraveled);
        fbb.addOffset(6, agencyIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final shapeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final agencyIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final latParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final lonParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final sequenceParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final distTraveledParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final object = Shape(
          id: idParam,
          shapeId: shapeIdParam,
          agencyId: agencyIdParam,
          lat: latParam,
          lon: lonParam,
          sequence: sequenceParam,
          distTraveled: distTraveledParam,
        );

        return object;
      },
    ),
    Stop: obx_int.EntityDefinition<Stop>(
      model: _entities[5],
      toOneRelations: (Stop object) => [],
      toManyRelations: (Stop object) => {},
      getId: (Stop object) => object.id,
      setId: (Stop object, int id) {
        object.id = id;
      },
      objectToFB: (Stop object, fb.Builder fbb) {
        final stopIdOffset = fbb.writeString(object.stopId);
        final codeOffset = object.code == null
            ? null
            : fbb.writeString(object.code!);
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final ttsNameOffset = object.ttsName == null
            ? null
            : fbb.writeString(object.ttsName!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final zoneIdOffset = object.zoneId == null
            ? null
            : fbb.writeString(object.zoneId!);
        final urlOffset = object.url == null
            ? null
            : fbb.writeString(object.url!);
        final parentStationOffset = object.parentStation == null
            ? null
            : fbb.writeString(object.parentStation!);
        final timezoneOffset = object.timezone == null
            ? null
            : fbb.writeString(object.timezone!);
        final levelIdOffset = object.levelId == null
            ? null
            : fbb.writeString(object.levelId!);
        final platformCodeOffset = object.platformCode == null
            ? null
            : fbb.writeString(object.platformCode!);
        final agencyIdOffset = object.agencyId == null
            ? null
            : fbb.writeString(object.agencyId!);
        fbb.startTable(18);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, stopIdOffset);
        fbb.addOffset(2, codeOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, ttsNameOffset);
        fbb.addOffset(5, descriptionOffset);
        fbb.addFloat64(6, object.latitude);
        fbb.addFloat64(7, object.longitude);
        fbb.addOffset(8, zoneIdOffset);
        fbb.addOffset(9, urlOffset);
        fbb.addInt64(10, object.locationType);
        fbb.addOffset(11, parentStationOffset);
        fbb.addOffset(12, timezoneOffset);
        fbb.addInt64(13, object.wheelchairBoarding);
        fbb.addOffset(14, levelIdOffset);
        fbb.addOffset(15, platformCodeOffset);
        fbb.addOffset(16, agencyIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final stopIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final agencyIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final ttsNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final zoneIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final locationTypeParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final parentStationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final timezoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final wheelchairBoardingParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 30);
        final levelIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final platformCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final object = Stop(
          id: idParam,
          stopId: stopIdParam,
          agencyId: agencyIdParam,
          code: codeParam,
          name: nameParam,
          ttsName: ttsNameParam,
          description: descriptionParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          zoneId: zoneIdParam,
          url: urlParam,
          locationType: locationTypeParam,
          parentStation: parentStationParam,
          timezone: timezoneParam,
          wheelchairBoarding: wheelchairBoardingParam,
          levelId: levelIdParam,
          platformCode: platformCodeParam,
        );

        return object;
      },
    ),
    StopTime: obx_int.EntityDefinition<StopTime>(
      model: _entities[6],
      toOneRelations: (StopTime object) => [object.trip, object.stop],
      toManyRelations: (StopTime object) => {},
      getId: (StopTime object) => object.id,
      setId: (StopTime object, int id) {
        object.id = id;
      },
      objectToFB: (StopTime object, fb.Builder fbb) {
        final tripGtfsIdOffset = fbb.writeString(object.tripGtfsId);
        final arrivalTimeOffset = object.arrivalTime == null
            ? null
            : fbb.writeString(object.arrivalTime!);
        final departureTimeOffset = object.departureTime == null
            ? null
            : fbb.writeString(object.departureTime!);
        final stopGtfsIdOffset = object.stopGtfsId == null
            ? null
            : fbb.writeString(object.stopGtfsId!);
        final locationGroupIdOffset = object.locationGroupId == null
            ? null
            : fbb.writeString(object.locationGroupId!);
        final locationIdOffset = object.locationId == null
            ? null
            : fbb.writeString(object.locationId!);
        final stopHeadsignOffset = object.stopHeadsign == null
            ? null
            : fbb.writeString(object.stopHeadsign!);
        final startPickupDropOffWindowOffset =
            object.startPickupDropOffWindow == null
            ? null
            : fbb.writeString(object.startPickupDropOffWindow!);
        final endPickupDropOffWindowOffset =
            object.endPickupDropOffWindow == null
            ? null
            : fbb.writeString(object.endPickupDropOffWindow!);
        final pickupBookingRuleIdOffset = object.pickupBookingRuleId == null
            ? null
            : fbb.writeString(object.pickupBookingRuleId!);
        final dropOffBookingRuleIdOffset = object.dropOffBookingRuleId == null
            ? null
            : fbb.writeString(object.dropOffBookingRuleId!);
        fbb.startTable(22);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, tripGtfsIdOffset);
        fbb.addOffset(2, arrivalTimeOffset);
        fbb.addOffset(3, departureTimeOffset);
        fbb.addOffset(4, stopGtfsIdOffset);
        fbb.addOffset(5, locationGroupIdOffset);
        fbb.addOffset(6, locationIdOffset);
        fbb.addInt64(7, object.stopSequence);
        fbb.addOffset(8, stopHeadsignOffset);
        fbb.addOffset(9, startPickupDropOffWindowOffset);
        fbb.addOffset(10, endPickupDropOffWindowOffset);
        fbb.addInt64(11, object.pickupType);
        fbb.addInt64(12, object.dropOffType);
        fbb.addInt64(13, object.continuousPickup);
        fbb.addInt64(14, object.continuousDropOff);
        fbb.addFloat64(15, object.shapeDistTraveled);
        fbb.addInt64(16, object.timepoint);
        fbb.addOffset(17, pickupBookingRuleIdOffset);
        fbb.addOffset(18, dropOffBookingRuleIdOffset);
        fbb.addInt64(19, object.trip.targetId);
        fbb.addInt64(20, object.stop.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final tripGtfsIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final arrivalTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final departureTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final stopGtfsIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final locationGroupIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final locationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final stopSequenceParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final stopHeadsignParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final startPickupDropOffWindowParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final endPickupDropOffWindowParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final pickupTypeParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final dropOffTypeParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final continuousPickupParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          30,
        );
        final continuousDropOffParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final shapeDistTraveledParam = const fb.Float64Reader()
            .vTableGetNullable(buffer, rootOffset, 34);
        final timepointParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          36,
        );
        final pickupBookingRuleIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final dropOffBookingRuleIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final object = StopTime(
          id: idParam,
          tripGtfsId: tripGtfsIdParam,
          arrivalTime: arrivalTimeParam,
          departureTime: departureTimeParam,
          stopGtfsId: stopGtfsIdParam,
          locationGroupId: locationGroupIdParam,
          locationId: locationIdParam,
          stopSequence: stopSequenceParam,
          stopHeadsign: stopHeadsignParam,
          startPickupDropOffWindow: startPickupDropOffWindowParam,
          endPickupDropOffWindow: endPickupDropOffWindowParam,
          pickupType: pickupTypeParam,
          dropOffType: dropOffTypeParam,
          continuousPickup: continuousPickupParam,
          continuousDropOff: continuousDropOffParam,
          shapeDistTraveled: shapeDistTraveledParam,
          timepoint: timepointParam,
          pickupBookingRuleId: pickupBookingRuleIdParam,
          dropOffBookingRuleId: dropOffBookingRuleIdParam,
        );
        object.trip.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          42,
          0,
        );
        object.trip.attach(store);
        object.stop.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          44,
          0,
        );
        object.stop.attach(store);
        return object;
      },
    ),
    Trip: obx_int.EntityDefinition<Trip>(
      model: _entities[7],
      toOneRelations: (Trip object) => [object.route, object.calendar],
      toManyRelations: (Trip object) => {},
      getId: (Trip object) => object.id,
      setId: (Trip object, int id) {
        object.id = id;
      },
      objectToFB: (Trip object, fb.Builder fbb) {
        final tripIdOffset = fbb.writeString(object.tripId);
        final routeGtfsIdOffset = fbb.writeString(object.routeGtfsId);
        final serviceIdOffset = fbb.writeString(object.serviceId);
        final headsignOffset = object.headsign == null
            ? null
            : fbb.writeString(object.headsign!);
        final shortNameOffset = object.shortName == null
            ? null
            : fbb.writeString(object.shortName!);
        final blockIdOffset = object.blockId == null
            ? null
            : fbb.writeString(object.blockId!);
        final shapeIdOffset = object.shapeId == null
            ? null
            : fbb.writeString(object.shapeId!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, tripIdOffset);
        fbb.addOffset(2, routeGtfsIdOffset);
        fbb.addOffset(3, serviceIdOffset);
        fbb.addOffset(4, headsignOffset);
        fbb.addOffset(5, shortNameOffset);
        fbb.addInt64(6, object.directionId);
        fbb.addOffset(7, blockIdOffset);
        fbb.addOffset(8, shapeIdOffset);
        fbb.addInt64(9, object.wheelchairAccessible);
        fbb.addInt64(10, object.bikesAllowed);
        fbb.addInt64(11, object.carsAllowed);
        fbb.addInt64(12, object.route.targetId);
        fbb.addInt64(13, object.calendar.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final tripIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final routeGtfsIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final serviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final headsignParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final shortNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final directionIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final blockIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final shapeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final wheelchairAccessibleParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 22);
        final bikesAllowedParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final carsAllowedParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final object = Trip(
          id: idParam,
          tripId: tripIdParam,
          routeGtfsId: routeGtfsIdParam,
          serviceId: serviceIdParam,
          headsign: headsignParam,
          shortName: shortNameParam,
          directionId: directionIdParam,
          blockId: blockIdParam,
          shapeId: shapeIdParam,
          wheelchairAccessible: wheelchairAccessibleParam,
          bikesAllowed: bikesAllowedParam,
          carsAllowed: carsAllowedParam,
        );
        object.route.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        object.route.attach(store);
        object.calendar.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        object.calendar.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Agency] entity fields to define ObjectBox queries.
class Agency_ {
  /// See [Agency.id].
  static final id = obx.QueryIntegerProperty<Agency>(
    _entities[0].properties[0],
  );

  /// See [Agency.agencyId].
  static final agencyId = obx.QueryStringProperty<Agency>(
    _entities[0].properties[1],
  );

  /// See [Agency.agencyName].
  static final agencyName = obx.QueryStringProperty<Agency>(
    _entities[0].properties[2],
  );

  /// See [Agency.agencyUrl].
  static final agencyUrl = obx.QueryStringProperty<Agency>(
    _entities[0].properties[3],
  );

  /// See [Agency.agencyTimezone].
  static final agencyTimezone = obx.QueryStringProperty<Agency>(
    _entities[0].properties[4],
  );

  /// See [Agency.agencyLang].
  static final agencyLang = obx.QueryStringProperty<Agency>(
    _entities[0].properties[5],
  );

  /// See [Agency.agencyPhone].
  static final agencyPhone = obx.QueryStringProperty<Agency>(
    _entities[0].properties[6],
  );

  /// See [Agency.agencyFareUrl].
  static final agencyFareUrl = obx.QueryStringProperty<Agency>(
    _entities[0].properties[7],
  );

  /// See [Agency.agencyEmail].
  static final agencyEmail = obx.QueryStringProperty<Agency>(
    _entities[0].properties[8],
  );
}

/// [Calendar] entity fields to define ObjectBox queries.
class Calendar_ {
  /// See [Calendar.id].
  static final id = obx.QueryIntegerProperty<Calendar>(
    _entities[1].properties[0],
  );

  /// See [Calendar.serviceId].
  static final serviceId = obx.QueryStringProperty<Calendar>(
    _entities[1].properties[1],
  );

  /// See [Calendar.monday].
  static final monday = obx.QueryIntegerProperty<Calendar>(
    _entities[1].properties[2],
  );

  /// See [Calendar.tuesday].
  static final tuesday = obx.QueryIntegerProperty<Calendar>(
    _entities[1].properties[3],
  );

  /// See [Calendar.wednesday].
  static final wednesday = obx.QueryIntegerProperty<Calendar>(
    _entities[1].properties[4],
  );

  /// See [Calendar.thursday].
  static final thursday = obx.QueryIntegerProperty<Calendar>(
    _entities[1].properties[5],
  );

  /// See [Calendar.friday].
  static final friday = obx.QueryIntegerProperty<Calendar>(
    _entities[1].properties[6],
  );

  /// See [Calendar.saturday].
  static final saturday = obx.QueryIntegerProperty<Calendar>(
    _entities[1].properties[7],
  );

  /// See [Calendar.sunday].
  static final sunday = obx.QueryIntegerProperty<Calendar>(
    _entities[1].properties[8],
  );

  /// See [Calendar.startDate].
  static final startDate = obx.QueryStringProperty<Calendar>(
    _entities[1].properties[9],
  );

  /// See [Calendar.endDate].
  static final endDate = obx.QueryStringProperty<Calendar>(
    _entities[1].properties[10],
  );

  /// See [Calendar.agencyId].
  static final agencyId = obx.QueryStringProperty<Calendar>(
    _entities[1].properties[11],
  );
}

/// [CalendarDate] entity fields to define ObjectBox queries.
class CalendarDate_ {
  /// See [CalendarDate.id].
  static final id = obx.QueryIntegerProperty<CalendarDate>(
    _entities[2].properties[0],
  );

  /// See [CalendarDate.serviceId].
  static final serviceId = obx.QueryStringProperty<CalendarDate>(
    _entities[2].properties[1],
  );

  /// See [CalendarDate.date].
  static final date = obx.QueryStringProperty<CalendarDate>(
    _entities[2].properties[2],
  );

  /// See [CalendarDate.exceptionType].
  static final exceptionType = obx.QueryIntegerProperty<CalendarDate>(
    _entities[2].properties[3],
  );

  /// See [CalendarDate.agencyId].
  static final agencyId = obx.QueryStringProperty<CalendarDate>(
    _entities[2].properties[4],
  );
}

/// [Route] entity fields to define ObjectBox queries.
class Route_ {
  /// See [Route.id].
  static final id = obx.QueryIntegerProperty<Route>(_entities[3].properties[0]);

  /// See [Route.routeId].
  static final routeId = obx.QueryStringProperty<Route>(
    _entities[3].properties[1],
  );

  /// See [Route.routeShortName].
  static final routeShortName = obx.QueryStringProperty<Route>(
    _entities[3].properties[2],
  );

  /// See [Route.routeLongName].
  static final routeLongName = obx.QueryStringProperty<Route>(
    _entities[3].properties[3],
  );

  /// See [Route.routeDesc].
  static final routeDesc = obx.QueryStringProperty<Route>(
    _entities[3].properties[4],
  );

  /// See [Route.routeType].
  static final routeType = obx.QueryIntegerProperty<Route>(
    _entities[3].properties[5],
  );

  /// See [Route.routeUrl].
  static final routeUrl = obx.QueryStringProperty<Route>(
    _entities[3].properties[6],
  );

  /// See [Route.routeColor].
  static final routeColor = obx.QueryStringProperty<Route>(
    _entities[3].properties[7],
  );

  /// See [Route.routeTextColor].
  static final routeTextColor = obx.QueryStringProperty<Route>(
    _entities[3].properties[8],
  );

  /// See [Route.routeSortOrder].
  static final routeSortOrder = obx.QueryIntegerProperty<Route>(
    _entities[3].properties[9],
  );

  /// See [Route.continuousPickup].
  static final continuousPickup = obx.QueryIntegerProperty<Route>(
    _entities[3].properties[10],
  );

  /// See [Route.continuousDropOff].
  static final continuousDropOff = obx.QueryIntegerProperty<Route>(
    _entities[3].properties[11],
  );

  /// See [Route.networkId].
  static final networkId = obx.QueryStringProperty<Route>(
    _entities[3].properties[12],
  );

  /// See [Route.agency].
  static final agency = obx.QueryRelationToOne<Route, Agency>(
    _entities[3].properties[13],
  );

  /// See [Route.agencyIdString].
  static final agencyIdString = obx.QueryStringProperty<Route>(
    _entities[3].properties[14],
  );
}

/// [Shape] entity fields to define ObjectBox queries.
class Shape_ {
  /// See [Shape.id].
  static final id = obx.QueryIntegerProperty<Shape>(_entities[4].properties[0]);

  /// See [Shape.shapeId].
  static final shapeId = obx.QueryStringProperty<Shape>(
    _entities[4].properties[1],
  );

  /// See [Shape.lat].
  static final lat = obx.QueryDoubleProperty<Shape>(_entities[4].properties[2]);

  /// See [Shape.lon].
  static final lon = obx.QueryDoubleProperty<Shape>(_entities[4].properties[3]);

  /// See [Shape.sequence].
  static final sequence = obx.QueryIntegerProperty<Shape>(
    _entities[4].properties[4],
  );

  /// See [Shape.distTraveled].
  static final distTraveled = obx.QueryDoubleProperty<Shape>(
    _entities[4].properties[5],
  );

  /// See [Shape.agencyId].
  static final agencyId = obx.QueryStringProperty<Shape>(
    _entities[4].properties[6],
  );
}

/// [Stop] entity fields to define ObjectBox queries.
class Stop_ {
  /// See [Stop.id].
  static final id = obx.QueryIntegerProperty<Stop>(_entities[5].properties[0]);

  /// See [Stop.stopId].
  static final stopId = obx.QueryStringProperty<Stop>(
    _entities[5].properties[1],
  );

  /// See [Stop.code].
  static final code = obx.QueryStringProperty<Stop>(_entities[5].properties[2]);

  /// See [Stop.name].
  static final name = obx.QueryStringProperty<Stop>(_entities[5].properties[3]);

  /// See [Stop.ttsName].
  static final ttsName = obx.QueryStringProperty<Stop>(
    _entities[5].properties[4],
  );

  /// See [Stop.description].
  static final description = obx.QueryStringProperty<Stop>(
    _entities[5].properties[5],
  );

  /// See [Stop.latitude].
  static final latitude = obx.QueryDoubleProperty<Stop>(
    _entities[5].properties[6],
  );

  /// See [Stop.longitude].
  static final longitude = obx.QueryDoubleProperty<Stop>(
    _entities[5].properties[7],
  );

  /// See [Stop.zoneId].
  static final zoneId = obx.QueryStringProperty<Stop>(
    _entities[5].properties[8],
  );

  /// See [Stop.url].
  static final url = obx.QueryStringProperty<Stop>(_entities[5].properties[9]);

  /// See [Stop.locationType].
  static final locationType = obx.QueryIntegerProperty<Stop>(
    _entities[5].properties[10],
  );

  /// See [Stop.parentStation].
  static final parentStation = obx.QueryStringProperty<Stop>(
    _entities[5].properties[11],
  );

  /// See [Stop.timezone].
  static final timezone = obx.QueryStringProperty<Stop>(
    _entities[5].properties[12],
  );

  /// See [Stop.wheelchairBoarding].
  static final wheelchairBoarding = obx.QueryIntegerProperty<Stop>(
    _entities[5].properties[13],
  );

  /// See [Stop.levelId].
  static final levelId = obx.QueryStringProperty<Stop>(
    _entities[5].properties[14],
  );

  /// See [Stop.platformCode].
  static final platformCode = obx.QueryStringProperty<Stop>(
    _entities[5].properties[15],
  );

  /// See [Stop.agencyId].
  static final agencyId = obx.QueryStringProperty<Stop>(
    _entities[5].properties[16],
  );
}

/// [StopTime] entity fields to define ObjectBox queries.
class StopTime_ {
  /// See [StopTime.id].
  static final id = obx.QueryIntegerProperty<StopTime>(
    _entities[6].properties[0],
  );

  /// See [StopTime.tripGtfsId].
  static final tripGtfsId = obx.QueryStringProperty<StopTime>(
    _entities[6].properties[1],
  );

  /// See [StopTime.arrivalTime].
  static final arrivalTime = obx.QueryStringProperty<StopTime>(
    _entities[6].properties[2],
  );

  /// See [StopTime.departureTime].
  static final departureTime = obx.QueryStringProperty<StopTime>(
    _entities[6].properties[3],
  );

  /// See [StopTime.stopGtfsId].
  static final stopGtfsId = obx.QueryStringProperty<StopTime>(
    _entities[6].properties[4],
  );

  /// See [StopTime.locationGroupId].
  static final locationGroupId = obx.QueryStringProperty<StopTime>(
    _entities[6].properties[5],
  );

  /// See [StopTime.locationId].
  static final locationId = obx.QueryStringProperty<StopTime>(
    _entities[6].properties[6],
  );

  /// See [StopTime.stopSequence].
  static final stopSequence = obx.QueryIntegerProperty<StopTime>(
    _entities[6].properties[7],
  );

  /// See [StopTime.stopHeadsign].
  static final stopHeadsign = obx.QueryStringProperty<StopTime>(
    _entities[6].properties[8],
  );

  /// See [StopTime.startPickupDropOffWindow].
  static final startPickupDropOffWindow = obx.QueryStringProperty<StopTime>(
    _entities[6].properties[9],
  );

  /// See [StopTime.endPickupDropOffWindow].
  static final endPickupDropOffWindow = obx.QueryStringProperty<StopTime>(
    _entities[6].properties[10],
  );

  /// See [StopTime.pickupType].
  static final pickupType = obx.QueryIntegerProperty<StopTime>(
    _entities[6].properties[11],
  );

  /// See [StopTime.dropOffType].
  static final dropOffType = obx.QueryIntegerProperty<StopTime>(
    _entities[6].properties[12],
  );

  /// See [StopTime.continuousPickup].
  static final continuousPickup = obx.QueryIntegerProperty<StopTime>(
    _entities[6].properties[13],
  );

  /// See [StopTime.continuousDropOff].
  static final continuousDropOff = obx.QueryIntegerProperty<StopTime>(
    _entities[6].properties[14],
  );

  /// See [StopTime.shapeDistTraveled].
  static final shapeDistTraveled = obx.QueryDoubleProperty<StopTime>(
    _entities[6].properties[15],
  );

  /// See [StopTime.timepoint].
  static final timepoint = obx.QueryIntegerProperty<StopTime>(
    _entities[6].properties[16],
  );

  /// See [StopTime.pickupBookingRuleId].
  static final pickupBookingRuleId = obx.QueryStringProperty<StopTime>(
    _entities[6].properties[17],
  );

  /// See [StopTime.dropOffBookingRuleId].
  static final dropOffBookingRuleId = obx.QueryStringProperty<StopTime>(
    _entities[6].properties[18],
  );

  /// See [StopTime.trip].
  static final trip = obx.QueryRelationToOne<StopTime, Trip>(
    _entities[6].properties[19],
  );

  /// See [StopTime.stop].
  static final stop = obx.QueryRelationToOne<StopTime, Stop>(
    _entities[6].properties[20],
  );
}

/// [Trip] entity fields to define ObjectBox queries.
class Trip_ {
  /// See [Trip.id].
  static final id = obx.QueryIntegerProperty<Trip>(_entities[7].properties[0]);

  /// See [Trip.tripId].
  static final tripId = obx.QueryStringProperty<Trip>(
    _entities[7].properties[1],
  );

  /// See [Trip.routeGtfsId].
  static final routeGtfsId = obx.QueryStringProperty<Trip>(
    _entities[7].properties[2],
  );

  /// See [Trip.serviceId].
  static final serviceId = obx.QueryStringProperty<Trip>(
    _entities[7].properties[3],
  );

  /// See [Trip.headsign].
  static final headsign = obx.QueryStringProperty<Trip>(
    _entities[7].properties[4],
  );

  /// See [Trip.shortName].
  static final shortName = obx.QueryStringProperty<Trip>(
    _entities[7].properties[5],
  );

  /// See [Trip.directionId].
  static final directionId = obx.QueryIntegerProperty<Trip>(
    _entities[7].properties[6],
  );

  /// See [Trip.blockId].
  static final blockId = obx.QueryStringProperty<Trip>(
    _entities[7].properties[7],
  );

  /// See [Trip.shapeId].
  static final shapeId = obx.QueryStringProperty<Trip>(
    _entities[7].properties[8],
  );

  /// See [Trip.wheelchairAccessible].
  static final wheelchairAccessible = obx.QueryIntegerProperty<Trip>(
    _entities[7].properties[9],
  );

  /// See [Trip.bikesAllowed].
  static final bikesAllowed = obx.QueryIntegerProperty<Trip>(
    _entities[7].properties[10],
  );

  /// See [Trip.carsAllowed].
  static final carsAllowed = obx.QueryIntegerProperty<Trip>(
    _entities[7].properties[11],
  );

  /// See [Trip.route].
  static final route = obx.QueryRelationToOne<Trip, Route>(
    _entities[7].properties[12],
  );

  /// See [Trip.calendar].
  static final calendar = obx.QueryRelationToOne<Trip, Calendar>(
    _entities[7].properties[13],
  );
}
